use crate::wave_table::{WaveTable, PERIOD_SAMPLES};
use crate::voice::Voice;

/// Naive pulse-width-modulated square wave.
///
/// Generated by direct piecewise definition rather than additive
/// synthesis: PWM at non-50% duty has discontinuities that are exactly
/// what gives it its character (the nasal "thinned out" quality
/// halfway between square and silence). Band-limiting it would smear
/// those edges and lose the effect; accepting the aliasing is the
/// standard cheap-and-cheerful approach. PolyBLEP is the proper fix
/// and could be added later.
///
/// Sample is `+amp` for the first `duty * len` samples of the period
/// and `-amp` for the rest. Phase rotates the period start.
pub struct Pwm { wavetable: WaveTable }

fn generate(
    frequency: f32,
    sample_rate: u16,
    amplitude: f32,
    phase: u8,
    duty: f32,
) -> WaveTable {
    let len = PERIOD_SAMPLES;
    let duty = duty.clamp(0.01, 0.99);
    let high_count = (len as f32 * duty) as usize;
    let phase_offset = ((phase as f32 / 256.0) * len as f32) as usize % len;

    let mut samples = vec![0f32; len];
    for i in 0..len {
	// Rotate the high region by the phase offset so the same
	// `phase` knob means the same thing across all voices.
	let j = (i + len - phase_offset) % len;
	samples[i] = if j < high_count { amplitude } else { -amplitude };
    }
    WaveTable::new(samples, frequency, sample_rate)
}

impl Pwm {
    pub fn new(
	frequency: f32,
	sample_rate: u16,
	amplitude: f32,
	phase: u8,
	duty: f32,
    ) -> Pwm {
	Pwm { wavetable: generate(frequency, sample_rate, amplitude, phase, duty) }
    }
}

impl Voice for Pwm {
    fn get_wavetable(self) -> WaveTable { self.wavetable }
}
