use crate::wave_table::{WaveTable, PERIOD_SAMPLES};
use crate::voice::Voice;

/// Band-limited sawtooth.
///
/// Generated by additive synthesis: a rising-sawtooth's Fourier
/// expansion is (2/π) Σ_{n=1..} (-1)^(n+1) sin(nθ)/n. Stop summing
/// at the highest n whose partial frequency stays below Nyquist;
/// peak-normalize; scale by amplitude.
pub struct Sawtooth { wavetable: WaveTable }

fn generate(frequency: f32, sample_rate: u16, amplitude: f32, phase: u8) -> WaveTable {
    let len = PERIOD_SAMPLES;
    let phi = phase as f32 / 256.0 * 2.0 * std::f32::consts::PI;
    let nyquist = sample_rate as f32 / 2.0;
    let max_n = ((nyquist / frequency).floor() as u32).max(1);

    let mut samples = vec![0f32; len];
    for n in 1..=max_n {
	let sign = if n % 2 == 1 { 1.0 } else { -1.0 };
	let coef = sign / n as f32;
	let nf = n as f32;
	for i in 0..len {
	    samples[i] += coef
		* (2.0 * std::f32::consts::PI * nf * i as f32 / len as f32 + phi).sin();
	}
    }

    let peak = samples.iter().fold(0.0f32, |m, v| m.max(v.abs()));
    if peak > 0.0 {
	let scale = amplitude / peak;
	for v in samples.iter_mut() {
	    *v *= scale;
	}
    }
    WaveTable::new(samples, frequency, sample_rate)
}

impl Sawtooth {
    pub fn new(frequency: f32, sample_rate: u16, amplitude: f32, phase: u8) -> Sawtooth {
	Sawtooth { wavetable: generate(frequency, sample_rate, amplitude, phase) }
    }
}

impl Voice for Sawtooth {
    fn get_wavetable(self) -> WaveTable { self.wavetable }
}
